services:

  db:
    image: postgres:16-bookworm
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis:7-bookworm
    # volumes:
    #   - redis-data:/data
    ports:
      - "6379:6379"
  
  opensearch:
    image: opensearchproject/opensearch:2.10.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "plugins.security.disabled=true"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.10.0
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "${DASHBOARD_PORT}:5601"
    depends_on:
      - opensearch
  
  kafka:
    image: redpandadata/redpanda:v25.2.1
    command: >
      redpanda start --overprovisioned
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
  kafka-console:
    image: redpandadata/console:v2.8.6
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "${CONSOLE_PORT}:8080"
    depends_on:
      - kafka

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.87.0
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics endpoint
  otel-collector-ui:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686" # Jaeger UI
    depends_on:
      - otel-collector
  prometheus:
    image: prom/prometheus:v2.53.1
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.0.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
  api:
    build: .
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - db
      - cache
      - opensearch
      - kafka
  